version: "3.8"

services:
  server-web:
    image: nginx:alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /app
