version: "3.8"

services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
