apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  type: ClusterIP
  selector:
    env: dev
    app: frontend
  ports:
    - port: 9000
      targetPort: 80
      protocol: TCP
      name: port-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: server-web
          image: nginx:alpine
