version: "3.8"

services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - ./env/mysql.env

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:18.19.1-alpine
    container_name: npm
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
