apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: super-secretos
  namespace: ns-dev
data:
  db_host: ZGV2LWRiLm1pZG9taW5pby5jb20=
  db_port: MzMwNg==
  db_user: dXNlcg==
  db_pass: MTIzNDU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set-frontend
  namespace: ns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      namespace: ns-dev
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: server-web
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: super-secretos
                  key: db_pass
