apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-set
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container01
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'pagina index ejecutada desde python' > index.html && python -m http.server 8082",
            ]
